### ISSUE TITLE
Human pilot == cheating?

### ISSUE THREAD

**Issue by colevscode** [chrislloyd/kepler#14]
With a decent display, there's nothing to stop someone from making a client that just maps mouse / key interactions to robot actions. This would basically turn the game into a top-down action RPG, instead of an AI contest. 

This assumes that piloting the bot is easier than writing an AI for the bot. I think this will be the case unless there are mechanics that make the game more suitable to AI clients. For example, unreasonably long play sessions where humans would get bored but enjoy checking in on their bot occasionally. Another example would be a really fast clock rate, think game of life, where decisions must be executed quickly just to keep the bot alive. 

Another alternative would be to design a sort of reverse-captcha: a problem that computers are better at solving than humans, that would filter out human pilots. However, this couldn't be implemented as a simple challenge to which the client must respond quickly, since the pilot-client could just automatically respond without the pilot's awareness. It would need to be more integrated into the game. For example a kind of in-game predator could occasionally chase bots that could be avoided with an algorithmic "juke" move. This would be an early challenge to survival, but the algorithm for avoiding the predator could be fairly obvious.

Or we could tell people not to pilot their bots because it's not the point of the game. Or maybe we're interested in having some human players and some bots. Perhaps the interaction would be interesting.

**Comment by lachlanhardy** [comment]
With Brains, Geoffrey Grosenbach wrote an iOS client that meant he could control his bot personally. He stood under the display screen with his phone and did it all manually. 

He was the only person who did it. Possibly because the iOS SDK was new and nobody was really into it yet. Even he was just doing as a way to learn Objective-C. 


Related: How about a bot leaderboard that displays the botname, author name, plus maybe a version number?

I think requiring a version number for bots might be a fascinating way of keeping track of people's effort versus results.

**Comment by chrislloyd** [comment]
@colevscode Human pilots — I'm all for them. The idea is that it's just a robot on another planet being piloted by a signal from Earth. However that signal is decided upon is up to the operator.

I think the difference in my thinking is highlighted when you said "AI contest" — it's  not really a contest. I do think though it may be easy to human operate a bot, a decent AI could defeat a human pretty easily. I have a few easy ideas to do that, but don't want to spoil strategy :)

@lachlanhardy A leaderboard of sorts is definitely a stretch goal. At the moment there's no concept of persistent identity in the game. When a connection to the game is established, a new identity is created. This makes it really easy for new players to get started, but difficult to do things like leaderboards. Another issue with the leaderboard is exactly what is being scored? One of the main goals of the game  (which I haven't really talked about a lot) is for the gameplay to be emergent. I want the bots to pick what goal is most important to them :)

**Comment by colevscode** [comment]
We could have a simple command that you can send to give your bot a name.

Also if human pilots are a go, I'm going to make an example version of my
client that is a piloting interface.

Finally I think we need a mode the server can be in that will add a bunch
of test bots or something. Since you can only open one socket to the host,
it means testing my client with more interesting data is tough. I think I'd
need to spin up a bunch of dynos or something.

**Comment by colevscode** [comment]
I'm concerned that the gameplay goals are overly ambitious given the few
days left we have before the conf. You mentioned lasers, but it appears
they are a part of items or a tech tree that still needs to be implemented.

Is there a way we can prioritize a subset of functionality for the
conference, and then expand on that afterwards?

Like, for example, can we just identify a few items that can be picked up,
punt on the crafting part for now, and end up with something that lets bots
run around trying to survive and occasionally shooting each other as an
intermediate goal?

**Comment by chrislloyd** [comment]
@colevscode re: give name. I'm down for that. I'll add that to the todo list.

re: testing bots. One way to do that in the short term is just to open multiple connections to the server from your script. One of my stretch goals in the next few days is to get a simple "human" in the game. It basically just tries to attack you. My plan was to make them more sophisticated during the camp.

re: priorities. I've been working offline over the last couple of days but pushed up simple lazers. Every player starts off with an inventory (which has a lazer in it) and you can send a command `USE` with the lazer-id to fire it. I agree that some of the more complicated inventory functions can be punted on. Once I get some "zombie humans" in there I'm going to scrap the solar radiation decay (or just made it very small).

You can see a rough todo list in the [readme.org](https://raw.githubusercontent.com/chrislloyd/kepler/master/README.org) (view it raw, github has weird org-mode formatting).

**Comment by chrislloyd** [comment]
Also, your renderer is awesome and I've been working on a little system for the docs page so that people can experiment with a basic bot without having to do too much work:

<img width="885" alt="screen shot 2015-09-08 at 11 00 22 am" src="https://cloud.githubusercontent.com/assets/718/9743019/dda88832-5618-11e5-9f36-8a6a40f20db1.png">

I'd love it if you kept working on it!

**Comment by colevscode** [comment]
I don't think you can open multiple websocket connections from the same or
even different browsers. In my testing, as soon as I open the second
connection via a second browser, the first one stops receiving messages.

**Comment by chrislloyd** [comment]
Is that an issue with kepler or are you just saying you generally can't do it?

**Comment by chrislloyd** [comment]
@colevscode multiple connection issue is fixed + human controllers are encouraged :) If our programs can't beat a human then we've got a long way to go.

@lachlanhardy I've been thinking about a leaderboard some more. I like the idea of self-declaring a name to keep the protocol simple. I've also been thinking about what a good scoring heuristic for the leaderboard could be. Originally for Brains we had _# of kills_, but I think it would be better if we made it _time alive_. We're all just trying to [stay alive](https://www.youtube.com/watch?v=I_izvAbhExY). What do you think?
