### ISSUE TITLE
Only last 2 connections get sent state updates

### ISSUE THREAD

**Issue by chrislloyd** [chrislloyd/kepler#16]
Effectively killing the bot. Pretty major issue. Reproducible by opening multiple connections. The first will die with the 3rd open, 2nd with the fourth and so on.

**Comment by chrislloyd** [comment]
This could be related to the what @colevscode was describing in #14

**Comment by colevscode** [comment]
Yeah this seems like what I was experiencing. Just two active bots at any
given time.

**Comment by chrislloyd** [comment]
This was surprisingly easy to fix :)
