### ISSUE TITLE
Sample client + renderer

### ISSUE THREAD

**Issue by chrislloyd** [chrislloyd/kepler#4]
It would be awesome to get a sample client to get people started. Probably one in JS and probably one in JS. It doesn't have to do very much, but should include a decent structure and have code to do all the actions described in #3.

(this next part seems like a tangent, but bear with me)

One change that I've made this year is where the render goes. Rendering from the server machine (like Brains 1) is fine in an environment like Railscamp where that output is fully locked down and difficult to parse. It's too slow/difficult to scan the global information on the projectors (like positions of other bots) to be practical.

However, I'd like this to transcend Railscamp and have been thinking a lot about the problem. There are a few options:

1. Server creates visualization which is publicly accessible. That effectively means all bots have all information.
2. Bots create their own visualization. This means that when you run a bot you also have to spin up your own viz.

The reason why I bring this up here is because I think the second option is the way to go and in that case the sample client should ship with a simple visualizer. People can potentially upgrade it or write their own, but it should be enough to show wtf is going on. Thoughts?

/cc @toolmantim @whatupdave

**Comment by chrislloyd** [comment]
Here's an example client that just walks around randomly:

https://gist.github.com/chrislloyd/2af96d671126714304ac

It would be great if a simple system like this could be hooked up to a viz *hint hint*.

**Comment by colevscode** [comment]
Took your silly random bot and added a silly SVG map renderer:

https://github.com/colevscode/kepler-client-react

It's really silly. 

Is there anywhere that lays out valid commands? All I know about is the move command from your example. (plz don't ask me to decipher your closure code..) Also what is in the state that's returned each tick? Here's what I'm seeing:

    {
      me: {
        pos: {x: 0, y: 0},
        life: 100
      },
      sensors: [ # some entities? 
        {
          pos: {x: 0, y: 0},
          ...?
        }
      ]
    }

Is that all? What else can a bot see?

Also, random bot just walks around and dies. How can the bot not die?

**Comment by chrislloyd** [comment]
I'm drunk at a wedding now but I love you Cole and will answer your
questions when I'm sober.

**Comment by chrislloyd** [comment]
Moving this discussion to github.com/chrislloyd/kepler-web.
